### ISSUE TITLE
Replace LiveReload with BrowserSync

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#103]
I think this would be cool to use [BrowserSync](http://www.browsersync.io/docs/grunt/) instead of LiveReload because it can do more: sync scroll, clicks, forms and other interaction between same page on different devices. (To control this there is web-based UI.)

All you have to do is launch BrowserSync before `watch` task.

I will experiment on this for productive discussion.

**Comment by larsonjj** [comment]
Browsersync is really awesome. I will try and look into it when I can. Thanks for bringing this to my attention :+1:

**Comment by Grawl** [comment]
I like Yeogurt very much, glad to help you improve it!

**Comment by larsonjj** [comment]
So I've been playing around with BrowserSync and it doesn't look good for trying to implement it within the generator. The reason for this is because I am using custom connect middleware within the `grunt-connect` plugin that mounts folders in a specific order like so :

```js
server: {
  options: {
    open: 'http://127.0.0.1:9010/',
    base: '<%= yeogurt.client %>',
    middleware: function(connect) {
      return [
        connect.static('.tmp'),
        connect().use('/bower_components', connect.static('./client/bower_components')),
        connect.static('client')
      ];
    }
  }
},
```

I'm trying to replicate this same functionality within the `[grunt-browser-sync](https://github.com/BrowserSync/grunt-browser-sync)` plugin, but haven't had any luck. @Grawl, maybe you could take a look and see if you have better luck getting it to work?

**Comment by Grawl** [comment]
I am haven't started new projects with updated Yeogurt since november and don't know: is this middleware used in static generator or somewhere other part. I don't seen this part before so I haven't seen any problems with BrowserSync integration.

**Comment by larsonjj** [comment]
Thanks again for bringing this to my attention. Feel free to submit a PR for a browsersync implementation (or guide) if you find the time.

Closing out.
