### ISSUE TITLE
React set page

### ISSUE THREAD

**Issue by seemsindie** [larsonjj/generator-yeogurt#105]
I am new to react and have not idea what i am doing, but i can see there is a action the set the page title and other info, how do i actually go about using that action?

And also setRoute, but i think that one is used internally for that router?

Thanks, Ivan.

**Comment by larsonjj** [comment]
So since you are using [React](http://facebook.github.io/react/), then you will also have [Flux](https://facebook.github.io/flux/) setup. The route and page actions you are referring to are pieces of Flux, so I would recommend reading up on it to answer most of your questions. [Stack Overflow](http://stackoverflow.com/) is also your friend :+1: 

For your current question, you can call actions by requiring them into your current components/scripts and calling their methods like so:

```js
var routeActions = require('../actions/routes');
var pageActions = require('../actions/page');

// This would tell the router to navigate to the settings page
routeActions.setRoute('/settings');

// Set page information
pageActions.set({title: 'Settings', description: 'The settings page', keywords: 'settings, page'});
```
