### ISSUE TITLE
React routing

### ISSUE THREAD

**Issue by tjslater** [larsonjj/generator-yeogurt#118]
I'm coming from using Angular every day, and was just experimenting with React, and I used the react sub-generator to create a new component (as outlined in the docs). However, it's not entirely clear how creating a new component can lead to making a new route. I tried adding the route in routes.js, and the method that it calls is virtually identical to the one that renders the index view 
```
var TestComponent = React.createFactory(require('./components/testcomponent.jsx'));
```
then
```
var test = function(){ render(TestComponent); };
```
and in the routes object I added
```
'/test': test
```
but it doesn't work. Besides adding the component and adding the route, is there some third step I'm unaware of? If I add my test component to an existing route, it works fine, it's just any new route I create isn't recognized.

**Comment by larsonjj** [comment]
Hi @tjslater,

Can you post the contents of your `.yo-rc.json` file? (Remove any private info first)
It is located in the root folder of your generated project. It is also a hidden file, so you might need to enable hidden files for your file manager to view it.

This will help me debug and hopefully answer the question you've posed. Thanks!

**Comment by tjslater** [comment]
Sure enough!
```
{
  "generator-yeogurt": {
    "config": {
      "projectName": "office-365-sample",
      "versionControl": "git",
      "useServer": true,
      "dbOption": "mongodb",
      "dbHost": "localhost",
      "dbPort": "27017",
      "dbName": "yeogurt_db",
      "dbUser": "",
      "dbPass": "",
      "useAuth": true,
      "singlePageApplication": true,
      "jsFramework": "react",
      "useJsx": true,
      "cssOption": "less",
      "useJsdoc": true,
      "useKss": true,
      "useTesting": true,
      "testFramework": "jasmine",
      "jsOption": "browserify"
    },
    "version": "0.14.3"
  }
}
```

**Comment by tjslater** [comment]
Ok, perhaps I'm not very familiar with React or Flux semantics. 
I can get to the route if I:
1. Go to it by link from another page
2. Put a # before the url if I try to go to it directly: e.g. (/#test)

But going directly to '/test' always results in a 404, in Chrome, FF, and Safari. Is this normal behavior for React?

**Comment by larsonjj** [comment]
Hey @tjslater 

So the issue you are running into is the fact that HTML5 pushState is on by default. This means that when you go to a normal route (i.e. /test), the server is expecting to render a template. Because you do not have a server template rendering for that route, you will get a 404 not found page.

To remedy the issue, you need to create a `/test` route for your express server. So create a `test.js` file within the `server/routes/` folder and copy in the following contents:

```js
/**
 * Test Routes
 */

'use strict';

var testController = require('../controllers/test');

var routes = function(app) {

  // Test
  app.get('/test', testController.index);

};

module.exports = routes;
```

Then create a new `test.js` file within `server/controllers/` folder with the following contents:

```js
/**
 * Test Controller
 */

'use strict';

var settings = require('../config/env/default');
var path = require('path');

var testController = function(req, res) {
  // Render index.html to allow application to handle routing
  res.sendFile(path.join(settings.staticAssets, '/index.html'), { root: settings.root });
};

module.exports = {
  index: testController
};
```

This will now allow you to render your `/test` route without the 404 error.

If you don't want to use HTML5 pushState (i.e. use `/#test` hash routing) and/or avoid creating server routes for every page, then you can go into the `client/scripts/main.js` file and change the `html5history: true` to `html5history: false`

**Comment by tjslater** [comment]
Thanks! That did the trick. I suppose I didn't realize what was involved in creating routes in this stack, a bit different than what I'm accustomed to! Cheers.
