### ISSUE TITLE
Running server in production mode, static resources 404 error

### ISSUE THREAD

**Issue by viewplatgh** [larsonjj/generator-yeogurt#140]
Using `grunt serve` is OK, everything is normal;  that's in development mode.
However, using `grunt serve:dist`, or go to dist folder and run `node server.js`. bower javascript components and fonts are not served, which cause 404 errors when visiting the site .

    GET /bower_components/jquery/jquery.js 404 7ms - 138b
    GET /fonts/fontawesome-webfont.woff?v=4.0.3 404 4ms - 138b

Add following two lines in server.js also not helping

    app.use(express.static(__dirname + '/client'));
    app.use(express.static(__dirname + '/client/styles'));

I am using Backbone, requirejs and express/mongodb.

This could be a bug, so I post here rather than in Stackoverflow.

Thanks!

**Comment by larsonjj** [comment]
Could you post your `.yo-rc.json` file? This will help me debug the issue you are having.

**Comment by viewplatgh** [comment]
It's like this. I removed db related settings.

{
  "generator-yeogurt": {
    "config": {
      "projectName": "wrwd",
      "versionControl": "git",
      "useServer": true,
      "dbOption": "",
      "dbHost": "",
      "dbPort": "",
      "dbName": "",
      "dbUser": "",
      "dbPass": "",
      "useAuth": true,
      "singlePageApplication": true,
      "jsFramework": "backbone",
      "jsTemplate": "handlebars",
      "jsOption": "requirejs",
      "cssOption": "less",
      "useJsdoc": true,
      "useKss": true,
      "useTesting": true,
      "testFramework": "mocha"
    },
    "version": "0.14.6"
  }
}

**Comment by viewplatgh** [comment]
`git clone -b yeogurt-bb https://github.com/viewplatgh/wrwd.git` should be able get the full source code.

**Comment by larsonjj** [comment]
Hey @viewplatgh,

It looks like you are using RequireJS's configuration for third-party/global libs (jquery, jstree, etc). This is the issue since you should be using the usemin blocks (`<!-- build:js -->`) within your `index.html` file to load your third-party scripts.

So Remove:

```js
// main.js
paths: {
    jquery: '../bower_components/jquery/jquery',
    jquery_cookie: '../bower_components/jquery.cookie/jquery.cookie',
    jquery_ui: '../bower_components/jquery-ui/ui/jquery-ui',
    jquery_layout: '../bower_components/jquery-layout/source/stable/jquery.layout_and_plugins',
    jstree: '../bower_components/jstree/dist/jstree',
    ace: '../bower_components/ace-builds/src/ace',
    can: '../bower_components/canjs/amd/can',
    sprintf: '../bower_components/sprintf/src/sprintf',
    getopt: 'getopt',
    wrwd: 'wrwd'
  },
  shim: {
    wrwd: {
      deps: ['jquery_cookie', 'jstree', 'ace', 'sprintf', 'getopt', 'can'],
    },
    jstree: {
      deps: ['jquery_layout'],
    },
    jquery_layout: {
      deps: ['jquery', 'jquery_ui'],
    },
    ace: {
      deps: ['jquery'],
    },
  }
```
And edit your `index.html` to look something like this:

```html
<!-- build:js({client,.tmp}) scripts/global.js -->
      <!-- bower:js -->
      <script src="/bower_components/jquery/jquery.js"></script>
      <script src="/bower_components/jquery.cookie/jquery.cookie.js"></script>
      <script src="/bower_components/underscore/underscore.js"></script>
      <script src="/bower_components/backbone/backbone.js"></script>
      <script src="/bower_components/handlebars/handlebars.runtime.js"></script>
      <script src="/bower_components/canjs/can.jquery.js"></script>
      <script src="/bower_components/jquery-ui/ui/jquery-ui.js"></script>
      <script src="/bower_components/jstree/dist/jstree.js"></script>
      <script src="/bower_components/sprintf/src/sprintf.js"></script>
      <!-- endbower -->
      <script src="/bower_components/ace-builds/src/ace.js"></script>
      <script src="/bower_components/canjs/can.jquery.js"></script>
      <script src="/bower_components/jquery-layout/source/stable/jquery.layout_and_plugins.js"></script>
      <script src="/scripts/getopt.js"></script>
      <script src="/scripts/wrwd.js"></script>
    <script src="/templates/templates.js"></script>
    <!-- endbuild -->
```

Even after making the above changes, you will have some errors based on your `wrwd.js` file because it is making requirejs calls to the third party scripts. You can remedy this by just using the global objects that the third-party libs create (ex. jquery attaches to `window.$ and window.jQuery`)

Hopefully that makes sense. This issue you are having is technically not a bug, just a process issue. If you follow the mantra that all global/third-party scripts are loaded within `index.html` and you just use their `window.*` object references in your scripts, you should be able to get up and running in both `grunt serve` and `grunt serve:dist`
