### ISSUE TITLE
Add --destination and --temporary args

### ISSUE THREAD

**Issue by OnkelTem** [larsonjj/generator-yeogurt#153]
I use my custom deployment system (a set of Bash scripts) which uses temporary directories when deploying websites. It's a convenient way when you need to adapt your build before uploading to a server, essentially they are: removing unnecessary files and adapt runtime config files a site may have (like DB-credentials and etc).

`yeogurt` can easily build a website wherever you point - both for production and temporary (development) builds, but `gulpfile.js` reads its arguments only from `project.json`.

It won't hurt anything if it can read the mentioned targets from the args. The fix seems quite simple to me, as this:

```
var taskTarget = args.production ? dirs.destination : dirs.temporary;
```

becomes:

```
var taskTarget = args.production ? (args.destination ? args.destination : dirs.destination) : (args.temporary ? args.temporary : dirs.temporary);
```

Thoughts?

**Comment by larsonjj** [comment]
Hey @OnkelTem,

I think this could be useful, but since it's a very custom need and such an easy update to the gulpfile, it seems that it might be better to add this information as a [guide](https://github.com/larsonjj/generator-yeogurt#guides). Rather than add it as a default to yeogurt.

Maybe with a title of: `Updating project configuration from CLI`?

I think would also be useful as it gives insight as to how the gulpfile tasks work regarding `args`.

Does that make sense?

**Comment by OnkelTem** [comment]
Yep, my example is just a particular case and is a part of more generic problem of reading project configuration from CLI, so — I agree with you.

**Comment by larsonjj** [comment]
Hey @OnkelTem,

I know this issue is kind of old, but would you want to write a guide in the README section on how to update project configuration from the CLI?

I think that could benefit some users.

**Comment by larsonjj** [comment]
Closing out due to inactivity.
