### ISSUE TITLE
Is there a way to use .html instead of .nunjucks

### ISSUE THREAD

**Issue by christiansakai** [larsonjj/generator-yeogurt#173]
I tried to change the extension of the src files from .nunjucks and .html, also changed the some of the gulpfile related to that. Seems not working.  Any ideas?

**Comment by larsonjj** [comment]
Hi @christiansakai,

Apologies for the late response. If you would like to use the `.html` extension instead of `.nunjucks`, you will need to:

- Rename the `base`, `link`, and `index` nunjucks files to `.html`
- Update the gulp `nunjuck.js` task file to look for `**/*.html` instead of `**/*.nunjucks`

Once those things are completed, everything will work as expected.

> NOTE: Keep in mind, if you use the sub-generators, they will create `.nunjucks` files, so will have to rename those files if you use them.

Hope this helps!

Closing out.

**Comment by netalex** [comment]
i'm wondering, can't that could be set in a general configuration var of sort? does'nt know yeogurt enoigh, but that would help not to have to rememebr changinng subgenerators template generated extension.
