### ISSUE TITLE
Not using html preprocessors

### ISSUE THREAD

**Issue by be-codified** [larsonjj/generator-yeogurt#174]
Is there a way to use this package without html preprocessors, like Jade? I would like to use simple html.

**Comment by larsonjj** [comment]
Hey @be-codified,

If you choose [`nunjucks`](https://mozilla.github.io/nunjucks/) instead of `jade`, it will allows you to write regular HTML with some extra logic functionality if you need it. To be honest though, HTML by itself (no logic) does not work super well with this generator as using modules and templates helps you create reusable code, and those require the extra logic from Jade or nunjucks.

**Comment by be-codified** [comment]
@larsonjj thank you for your reply.
