### ISSUE TITLE
Gulp Serve browsersync doesn't automatically update

### ISSUE THREAD

**Issue by JimTheMan** [larsonjj/generator-yeogurt#178]
Hi. I'm wondering how to tell browsersync to automatically update when I change a file. Right now when I make a change I see things happening in my command line, but the page doesn't refresh. I have to go over to the browser and hit the refresh button, but doesn't this defeat the whole purpose of browsersync? haha

**Comment by JimTheMan** [comment]
I did install this on a computer with an account that did not have sudo permissions. Could this be causing my issues?

**Comment by larsonjj** [comment]
Hey @JimTheMan,

Apologies for the late response. If you could post the contents of your `.yo-rc.json` file (located in the root folder of your project), that will help me recreate you project and try to troubleshoot your issue.

In the meantime, I would try upgrading browser-sync to the latest version via `npm install browser-sync --save-dev` and see if that helps. Also, this [issue](https://github.com/BrowserSync/browser-sync/issues/392#issuecomment-138419441) might shed some light on a fix. It incorporates the reloadDelay option.

Not having admin/sudo rights on a machine can cause file permission issues, so that definitely can lead to some issues. Unfortunately I wont be able to solve those specific problems.

Good Luck!

**Comment by larsonjj** [comment]
Closing out due to lack of response. Feel free to reopen @JimTheMan if you have more to add here.
