### ISSUE TITLE
Coding style stuck on spaces

### ISSUE THREAD

**Issue by sitrobotsit** [larsonjj/generator-yeogurt#193]
I've changed: 
indent_style = tab
indent_size = 4 
within .editorconfig at the root of the project, however all the files generated with yo yeorgurt:module... get generated with 2 spaces instead of tabs. Am I missing where to config this?

**Comment by larsonjj** [comment]
Hey @sitrobotsit,

Changing your `.editorconfig` to the those settings will ensure them the next time you save a file. This isn't ideal of course, because you don't want to open every file and re-save it (super annoying). The way I solve this problem is by using a RegExp in my code editor to Find and Replace All instances of indentation with what I want.

Use this RegExp to select all the "space" indentation: `^( {1})+`
And replace it with a tab character: `\t`

Example in Sublime text (will work in any editor with a similar interface):
<img width="640" alt="screen shot 2016-09-22 at 12 05 58 am" src="https://cloud.githubusercontent.com/assets/3893845/18737598/ba2612ec-8058-11e6-989b-0c2ba4dbc963.png">

> NOTE: The `Where` input here allows you to specify which files you want to apply this RegExp to. (`*.*` means all files in every folder)

Let me know if this helps.

**Comment by sitrobotsit** [comment]
Hey, thanks for the reply. So, this is what I'm doing

![1](https://cloud.githubusercontent.com/assets/856535/18775748/5732db98-81a7-11e6-8f01-63aa55a4a21c.PNG)

And then when I open the file, I get this
![2](https://cloud.githubusercontent.com/assets/856535/18775775/9505fc20-81a7-11e6-800b-5893c1f9b081.PNG)

Is there no way to get it to generate with tabs instead of spaces? The only way I can fix this is if I do; Edit > Line > Reindent

**Comment by larsonjj** [comment]
@sitrobotsit, currently there is no way to configure indentation when generating files. If you can figure out a good way to do so, I would welcome a PR 👍 .

Otherwise, for now you will just need to convert it yourself.

**Comment by larsonjj** [comment]
Closing out for now, feel free to reopen if you have more comments @sitrobotsit.
