### ISSUE TITLE
[Question] Semi-Dynamic Pages (for a Blog) from Data File

### ISSUE THREAD

**Issue by tfohlmeister** [larsonjj/generator-yeogurt#203]
I had no trouble creating multi-page website but can you guys give me a hint on how to implement a **blog** using this generator?

I know how to use data files and how to iterate over them so I can easily create an overview page with all of the blog entries. But how would I proceed to implement sub-pages for this blog to show each individual item from my data file?

The only thing I can imagine is to create a gulp task which reads my data file and creates `.jade` files out of it.

**Comment by felixyin** [comment]
me too..
help

**Comment by heitzke** [comment]
.. Technically not quite what we're looking for since it's not as automated as i'd like, but a step in the right direction. Right now i'm setting a variable in the data file for each entry that pulls in a uniquely named template partial. 

{% include '_layouts/test-content/' + val.hash + '.nunjucks' %}

One of those.. ugly.. but sort of works type solutions for now. It generates the rest of the surrounding content, but pulls in that entry specific content into the main body.

**Comment by xizhao** [comment]
I would just implement your own gulp build task that handles this separately.  There’s no way to do this with the current generators.
