### ISSUE TITLE
Coffeescript?

### ISSUE THREAD

**Issue by Grawl** [larsonjj/generator-yeogurt#62]
I love to write on preprocessors :laughing: so I love Coffee. and I love a coffee! 😂

**Comment by larsonjj** [comment]
As it stands now, I do not plan to support coffeescript. In the wake of ES6 and the ease of use through [Babel](http://babeljs.io/), I don't believe it's necessary to support CS out of the box. I think adding a [guide](https://github.com/larsonjj/generator-yeogurt/tree/master/docs/guides) on how to add CS support to a project would be more beneficial, so I will work on that going forward.

**Comment by Grawl** [comment]
Understand.
I tried do it by myself and even get some luck with [`grunt-coffee-chain`](https://github.com/rrott/grunt_coffee_chain) to control partials but don't sure that this is the right way to build CoffeeScript with Grunt. I tried `grunt-coffee-chain` because regular `grunt-contrib-coffee` compiles all partials in alphanumeric order but I want to control this like in Sass. Can you write a right guide @larsonjj?

**Comment by larsonjj** [comment]
Hey @Grawl, Sorry for the delayed response. I'm currently deep in development for v1.0.0 of this generator, so I will not have time to create a guide for adding coffeescript for a while. If you find success in an implementation of coffeescript for a yeogurt project, feel free to submit a PR. Otherwise I will be closing this out for now.
