### ISSUE TITLE
Feature request: Support for nunjucks

### ISSUE THREAD

**Issue by fusionstrings** [larsonjj/generator-yeogurt#82]
Although generator-yeogurt already supports plethora of options to choose and configure but here we would be glad to see one more, that is support of Nunjucks.

Yeogurt already supports swig but nunjucks is direct port of python Jinja2 and supported by Mozilla. It already got great documentation (I believe better than swig). So may be if you feel there is enough traction you might consider adding support for Nunjucks. As of now I see no yeoman generator supports this out of the box.

**Comment by larsonjj** [comment]
After a decent amount of research, I found that there aren't any grunt plugins available that currently work well with yeogurt in terms of compiling nunjucks templates to html. the only one that shows some promise is [grunt-nunjucks-2-html](https://github.com/vitkarpov/grunt-nunjucks-2-html) and unfortunately I only receive errors when trying to use it :cry:

I'm going to close this for now as I don't plan to support nunjucks for the time being due to the large effort it would take for me to create a custom plugin and/or contribute to existing implementations.

If you find a solution to solving the nunjucks -> HTML via grunt, please feel free to reopen this ticket and I will re-evaluate.
