### ISSUE TITLE
Are there plans to support coffeescript?

### ISSUE THREAD

**Issue by lispking** [larsonjj/generator-yeogurt#95]
rt

**Comment by larsonjj** [comment]
I am planning on adding coffeescript at some point. The real problem lies in adding it for use with Express/Node. It is quite a lot of work to re-write all the generated client/server code in coffeescript, so PRs are welcome :+1: 

You can read and continue the initial discussion [here](https://github.com/larsonjj/generator-yeogurt/issues/62)
