### ISSUE TITLE
Foundation and Sass stops grunt

### ISSUE THREAD

**Issue by Conrad777** [larsonjj/generator-yeogurt#97]
Hi, when generating a scaffold with Foundation using Sass it gives an error when running grunt.

I fixed it by changing the following inside my generated main.scss

`@import "../bower_components/foundation/scss/foundation/components/switch";`

to

`@import "../bower_components/foundation/scss/foundation/components/switches";`

Hope this is helpful...

**Comment by larsonjj** [comment]
Thanks for reporting this. Could you please post the contents of your .yo-rc.json file (you can remove any user and password info). That will help me debug this much easier.

*note: yo-rc file is a hidden file in the root directory of your generated project. You may need to enable hidden files in your file browser to see it

**Comment by Conrad777** [comment]
Hey, here's the latest one I generated. Yeogurt is awesome by the way...

```json
{
  "generator-yeogurt": {
    "config": {
      "projectName": "",
      "versionControl": "git",
      "useServer": false,
      "singlePageApplication": false,
      "htmlOption": "html",
      "jsOption": "browserify",
      "cssOption": "sass",
      "sassSyntax": "scss",
      "useBourbon": false,
      "cssFramework": "foundation",
      "useGA": true,
      "jshint": true,
      "extras": [],
      "useJsdoc": false,
      "useKss": false,
      "useDashboard": false,
      "useTesting": false,
      "useFTP": false
    },
    "version": "0.12.3"
  }
}
```

**Comment by larsonjj** [comment]
Awesome, thanks!

Looks like you are using an outdated version: `v0.12.3` vs `v0.13.6 (latest)`
Out-of-the-box support for Foundation has since been removed and a [Guide](https://github.com/larsonjj/generator-yeogurt/blob/master/docs/guides/foundation.md) has been set up in it's place. This is due to the directory structures and file names of bower components changing very often (hence the `switch` -> `switches` bug you found). The latest generator now uses [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep) to handle this as it will be more consistent at avoiding these type of bugs going forward.

I would suggest upgrading yeogurt to avoid this issue next time.

Thanks again for reporting this. If anyone else runs into this issue, they will be able to find this solution through an easy issue search.
