### ISSUE TITLE
grunt-contrib-watch, Firefox not responding, livereload interruption

### ISSUE THREAD

**Issue by scottjason** [larsonjj/generator-yeogurt#99]
Hey Jake, I'm getting this error in firefox (chrome ok re livereload):

"The connection to ws://localhost:35729/livereload was interrupted while the page was loading."

The error is also documented here but not sure what to do:
https://github.com/gruntjs/grunt-contrib-watch/issues/373

--

I was also getting this other error that's listed in SO in the chrome console:

http://stackoverflow.com/questions/26408931/bizarre-error-in-chrome-developer-console-failed-to-load-resource-neterr-ca

But seems to have gone away since I removed the caching settings you built into the express conifg. People seem to say it's just a warning from chrome but it was stalling the browser (spinny wheel). Just want to double check with you that these are indeed related. (or not)

Thanks!

**UPDATE**

So everything on chrome went to amazing (no hanging) with the following settings:

1. disable live reload in express conifg
2. in chrome console, under network tab, uncheck disable cache (is this what you already were doing in express config that I removed?)

Those two changes and chrome runs without hanging.

**Comment by larsonjj** [comment]
Hey thanks for reporting this.

I have also noticed that weird chrome cache error, but it didn't affect anything on my end, so I thought nothing of it. Also, it looks as though this bug has been fixed with Chrome v40, so if you update your chrome browser that should fix the issue.

> in chrome console, under network tab, uncheck disable cache (is this what you already were doing in express config that I removed?)

To answer your question: Yes, the cache settings in the express.js config file basically do the same thing as checking the "Disable cache" within dev tools. If you plan on having dev tools open all the time while developing then feel free to keep the express cache settings removed for your project.

> "The connection to ws://localhost:35729/livereload was interrupted while the page was loading."

This one is really weird as well and I am not exactly sure how to get the message to go away. Good news is that livereload seems to work fine with or without that message showing up. Maybe a firefox bug? I suggest you just ignore it for now.

I have done quite a bit of testing and it seems like all is well for now. Let me know if this helps solve your issue.

**Comment by scottjason** [comment]
OK, makes sense about the cache. I updated to chrome 40 and that message is gone (I could've sworn I already did that!) 

As for reload and firefox, yeah it is a totally weird one and that was the only browser that experienced it, so definitely could be a firefox bug.

I think overall I just had a weird combo going on with the chrome err, the cache settings and maybe a firefox bug but all is good now.

Thanks again!
